#ifndef _SIM808_H
#define _SIM808_H

#define UART_SIM808_TXD (CONFIG_UART_SIM808_TXD)
#define UART_SIM808_RXD (CONFIG_UART_SIM808_RXD)
#define UART_SIM808_RTS (UART_PIN_NO_CHANGE)
#define UART_SIM808_CTS (UART_PIN_NO_CHANGE)

#define UART_SIM808_PORT_NUM   (CONFIG_UART_SIM808_PORT_NUM)
#define UART_SIM808_BAUD_RATE  (CONFIG_UART_SIM808_BAUD_RATE)
#define ECHO_TASK_STACK_SIZE   (CONFIG_EXAMPLE_TASK_STACK_SIZE)
#define BUF_SIZE (1024)

void initialize_sim808Uart(void);
void setup_Sim808(void);

#endif // _SIM808_H
